name: Build and push Docker image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
      image_tag:
        description: 'Optional explicit image tag to push (if empty, will push latest and commit-sha)'
        required: false

env:
  DOCKERHUB_REPO: outlmp/veloera-next

jobs:
  build_and_push:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save version info
        run: |
          # If there are no tags git describe would fail; use --always to fall back to commit SHA.
          git describe --tags --always --dirty > VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare image tags
        id: tags
        run: |
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            echo "TAGS=docker.io/${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.image_tag }},docker.io/${{ env.DOCKERHUB_REPO }}:latest" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAGS=docker.io/${{ env.DOCKERHUB_REPO }}:${SHORT_SHA},docker.io/${{ env.DOCKERHUB_REPO }}:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache || true
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
